### ISSUE TITLE
Handle null values gracefully

### ISSUE THREAD

**Issue by justinbach** [inadarei/kokua#1]
Currently, using an input with a property mapped to a null value throws an error.

Running this code
```javascript
const kokua = require('kokua');

const data = {
  foo: null,
};

kokua(data, kokua.mt('hal'));
```
results in this error being thrown:
```
/node_modules/kokua/lib/plugins/hal.js:148
          if (curr["h:ref"] || curr["h:link"]) {
                  ^

TypeError: Cannot read property 'h:ref' of null
```

**Comment by inadarei** [comment]
@justinbach many thanks for finding the exact issue here and providing a crystal-clear issue definition. That made fixing much, much easier. Appreciate it a lot.

**Comment by justinbach** [comment]
@inadarei sure thing! Thanks for the quick fix.
